### ISSUE TITLE
Merge blocks issue

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/numba#45] opened 2017-11-14 03:32 UTC
The following code fails after commit bc252cca20d23b3d249b213605247f90de61473e.

```python
import numpy as np
import numba
numba.parfor.sequential_parfor_lowering = True

@numba.njit(parallel=True)
def f():
    A = np.array([1., 2., 3.])
    A[0] = np.nan
    count = 0
    s = 0
    for i in numba.parfor.prange(len(A)):
        val = A[i]
        if not np.isnan(val):
            s += val
            count += 1
    if not count:
        s = np.nan
    res = s
    return res

print(f())
```
```
  File "/Users/etotoni/pse-hpc/python/numba/numba/compiler.py", line 494, in stage_parfor_pass
    parfor_pass.run()
  File "/Users/etotoni/pse-hpc/python/numba/numba/parfor.py", line 309, in run
    self.typingctx, self.func_ir, self.typemap, self.calltypes)
  File "/Users/etotoni/pse-hpc/python/numba/numba/parfor.py", line 1461, in lower_parfor_sequential
    func_ir.blocks = rename_labels(func_ir.blocks)
  File "/Users/etotoni/pse-hpc/python/numba/numba/ir_utils.py", line 1075, in rename_labels
    term.target = label_map[term.target]
KeyError: 'Failed at nopython (convert to parfors)\n4'
```

**Comment by ninegua** [comment] 2017-11-14 07:05
The issue is with `rename_labels` always starts from label 0. Also I think it is better to enforce `_max_label` is never reset.

The fix is in c9e83c423626627085b047e6a64c9ab7b8f28c25.

**Closed as completed** 2017-11-16 20:39 UTC
